---
- hosts: all
  user: ansadmin
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Execute a command that will fail
      command: ls -blt
      ignore_errors: yes
    - name: Install git
      yum: pkg=git state=installed