--- # this is my first playbook
- hosts: all
  user: ansadmin
  become: true
  connection: ssh
  gather_facts: no
  tasks:
   - name: Uninstall git software on host systems
     yum: pkg=git state=absent
   - name: Uninstall httpd software on host systems
     yum: pkg=httpd state=absent
